model_family: llama2-7b
<<<<<<< HEAD
=======
mode: qa

data_path: locuslab/TOFU
forget_data_path: /home/jylee/SUN/data/forget_set/text/forget10_texts.json
retain_data_path: /home/jylee/SUN/data/retain_set/text/retain90_texts.json
>>>>>>> Update with new code from Cursor

batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 20
lr: 1e-5
<<<<<<< HEAD
save_dir: /home/jylee/SUN/finetuned_model/retrained_model/ft_epoch${num_epochs}_lr${lr}_wd${weight_decay}
=======
save_dir: /mnt/sdd1/jylee/finetuned_model/mode${mode}/ft_epoch${num_epochs}_lr${lr}_wd${weight_decay}
>>>>>>> Update with new code from Cursor

weight_decay: 0.01
seed: 42